version: '3'

tasks:

  run:
    cmds:
      - go run .

  build:
    cmds:
      - go build -o multipasser
      - echo "Build complete. Run ./multipasser to start the application."
      
  build-all:
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -o multipasser-macos-arm64
      - GOOS=darwin GOARCH=amd64 go build -o multipasser-macos-amd64
      - GOOS=linux GOARCH=arm64 go build -o multipasser-linux-arm64
      - GOOS=linux GOARCH=amd64 go build -o multipasser-linux-amd64
      - GOOS=windows GOARCH=arm64 go build -o multipasser-windows-arm64.exe
      - GOOS=windows GOARCH=amd64 go build -o multipasser-windows-amd64.exe

  delete-builds:
    cmds:
      - rm -f multipasser-macos-arm64 multipasser-macos-amd64 multipasser-linux-arm64 multipasser-linux-amd64 multipasser-windows-arm64.exe multipasser-windows-amd64.exe
      - echo "All builds deleted."